import { StyleSheet } from 'react-native';
import theme from '../theme';

export default StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: theme.colors.white,
  },
  scrollContent: {
    padding: 16,
    paddingBottom: 40,
  },
  center: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 24,
  },
  loadingText: {
    marginTop: 12,
    fontSize: 13,
    color: theme.colors.gray600,
  },
  
  // Greeting Banner
  banner: {
    backgroundColor: '#0d1b2a',
    borderWidth: 1.5,
    borderColor: theme.colors.black,
    borderRadius: theme.radii.base,
    padding: 20,
    marginBottom: 20,
    position: 'relative',
    overflow: 'hidden',
    ...theme.shadows.base,
  },
  bannerSubtitle: {
    fontSize: 10,
    fontWeight: theme.typography.fontBlack,
    textTransform: 'uppercase',
    letterSpacing: 2,
    color: theme.colors.gray400,
    marginBottom: 4,
  },
  bannerTitle: {
    fontSize: 22,
    fontWeight: theme.typography.fontBlack,
    color: theme.colors.white,
    marginBottom: 12,
  },
  badgeRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  tierBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 215, 0, 0.15)',
    borderWidth: 1,
    borderColor: '#ffd700',
    paddingVertical: 4,
    paddingHorizontal: 10,
    borderRadius: 99,
  },
  tierText: {
    color: '#ffd700',
    fontSize: 10,
    fontWeight: theme.typography.fontBold,
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  cartBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.08)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.15)',
    paddingVertical: 4,
    paddingHorizontal: 10,
    borderRadius: 99,
  },
  cartBtnText: {
    color: theme.colors.white,
    fontSize: 10,
    fontWeight: theme.typography.fontBold,
    textTransform: 'uppercase',
    letterSpacing: 1,
    marginLeft: 4,
  },

  // Next Event Hero
  sectionLabel: {
    fontSize: 11,
    fontWeight: theme.typography.fontBlack,
    textTransform: 'uppercase',
    letterSpacing: 3,
    color: theme.colors.gray500,
    marginBottom: 8,
    marginTop: 10,
  },
  heroCard: {
    height: 180,
    borderRadius: theme.radii.base,
    overflow: 'hidden',
    borderWidth: 1.5,
    borderColor: theme.colors.black,
    marginBottom: 20,
    position: 'relative',
    ...theme.shadows.md,
  },
  heroImage: {
    position: 'absolute',
    inset: 0,
    width: '100%',
    height: '100%',
  },
  heroGradient: {
    position: 'absolute',
    inset: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.65)',
  },
  heroContent: {
    position: 'absolute',
    inset: 0,
    padding: 16,
    justifyContent: 'flex-end',
  },
  heroSub: {
    fontSize: 9,
    fontWeight: theme.typography.fontBold,
    textTransform: 'uppercase',
    letterSpacing: 2,
    color: theme.colors.gray300,
    marginBottom: 2,
  },
  heroTitle: {
    fontSize: 18,
    fontWeight: theme.typography.fontBlack,
    color: theme.colors.white,
    marginBottom: 4,
  },
  heroMeta: {
    fontSize: 11,
    color: theme.colors.gray300,
    fontWeight: theme.typography.fontSemibold,
    marginBottom: 8,
  },
  heroFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  countdownPill: {
    backgroundColor: 'rgba(0, 0, 0, 0.75)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.2)',
    borderRadius: 8,
    paddingVertical: 4,
    paddingHorizontal: 8,
    alignItems: 'center',
  },
  countdownVal: {
    fontSize: 12,
    fontWeight: theme.typography.fontBlack,
    color: theme.colors.white,
  },
  countdownSub: {
    fontSize: 6,
    fontWeight: theme.typography.fontBlack,
    color: theme.colors.gray400,
    letterSpacing: 1,
  },
  actionBtn: {
    backgroundColor: theme.colors.white,
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 8,
  },
  actionBtnText: {
    color: theme.colors.black,
    fontSize: 10,
    fontWeight: theme.typography.fontBlack,
    letterSpacing: 1,
  },

  // No tickets state
  noTicketsCard: {
    backgroundColor: theme.colors.gray50,
    borderWidth: 1.5,
    borderStyle: 'dashed',
    borderColor: theme.colors.gray300,
    borderRadius: theme.radii.base,
    padding: 24,
    alignItems: 'center',
    marginBottom: 20,
  },
  noTicketsEmoji: {
    fontSize: 32,
    marginBottom: 8,
  },
  noTicketsTitle: {
    fontSize: 13,
    fontWeight: theme.typography.fontBlack,
    color: theme.colors.black,
    letterSpacing: 1,
    marginBottom: 4,
    textTransform: 'uppercase',
  },
  noTicketsSub: {
    fontSize: 11,
    color: theme.colors.gray500,
    textAlign: 'center',
    marginBottom: 16,
  },
  exploreBtn: {
    paddingVertical: 8,
    paddingHorizontal: 18,
    backgroundColor: theme.colors.black,
    borderRadius: 99,
  },
  exploreBtnText: {
    color: theme.colors.white,
    fontSize: 10,
    fontWeight: theme.typography.fontBlack,
    letterSpacing: 1,
  },

  // Discover Section
  discoverGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    marginBottom: 20,
  },
  miniEventCard: {
    width: '48%',
    height: 180,
    borderRadius: theme.radii.base,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: theme.colors.gray200,
    position: 'relative',
    ...theme.shadows.sm,
  },
  miniImage: {
    position: 'absolute',
    inset: 0,
    width: '100%',
    height: '100%',
  },
  miniGradient: {
    position: 'absolute',
    inset: 0,
    backgroundColor: 'rgba(0,0,0,0.5)',
  },
  miniContent: {
    position: 'absolute',
    inset: 0,
    padding: 10,
    justifyContent: 'flex-end',
  },
  miniPrice: {
    position: 'absolute',
    top: 8,
    right: 8,
    backgroundColor: 'rgba(0,0,0,0.7)',
    paddingVertical: 2,
    paddingHorizontal: 6,
    borderRadius: 6,
    color: theme.colors.white,
    fontSize: 10,
    fontWeight: theme.typography.fontBlack,
  },
  miniTitle: {
    color: theme.colors.white,
    fontSize: 12,
    fontWeight: theme.typography.fontBold,
    marginBottom: 2,
  },
  miniMeta: {
    color: theme.colors.gray300,
    fontSize: 9,
    marginBottom: 6,
  },
  miniAddBtn: {
    backgroundColor: theme.colors.white,
    paddingVertical: 4,
    borderRadius: 6,
    alignItems: 'center',
  },
  miniAddText: {
    color: theme.colors.black,
    fontSize: 8,
    fontWeight: theme.typography.fontBlack,
    letterSpacing: 0.5,
  },

  // Activity Feed
  feedList: {
    gap: 8,
    marginBottom: 20,
  },
  feedItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.colors.gray50,
    borderWidth: 1,
    borderColor: theme.colors.gray200,
    borderRadius: theme.radii.sm,
    padding: 10,
  },
  feedImage: {
    width: 40,
    height: 40,
    borderRadius: 8,
    marginRight: 10,
  },
  feedInfo: {
    flex: 1,
  },
  feedTitle: {
    fontSize: 13,
    fontWeight: theme.typography.fontBold,
    color: theme.colors.black,
    marginBottom: 2,
  },
  feedCode: {
    fontSize: 10,
    color: theme.colors.gray500,
    fontFamily: 'System',
  },
  feedRight: {
    alignItems: 'flex-end',
  },
  feedPrice: {
    fontSize: 13,
    fontWeight: theme.typography.fontBlack,
    color: theme.colors.black,
  },
});
