import { StyleSheet } from 'react-native';
import theme from '../../theme';

export default StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: theme.colors.white,
  },
  scrollContent: {
    padding: 16,
    paddingBottom: 40,
  },
  welcomeBanner: {
    backgroundColor: theme.colors.gray50,
    borderWidth: 1.5,
    borderColor: theme.colors.black,
    borderRadius: theme.radii.base,
    padding: 18,
    marginBottom: 20,
    ...theme.shadows.sm,
  },
  welcomeGreeting: {
    fontSize: 20,
    fontWeight: theme.typography.fontBlack,
    color: theme.colors.black,
  },
  welcomeDate: {
    fontSize: 12,
    color: theme.colors.gray500,
    marginTop: 4,
  },
  sectionTitle: {
    fontSize: 13,
    fontWeight: theme.typography.fontBlack,
    letterSpacing: 1.5,
    marginBottom: 12,
    color: theme.colors.black,
    textTransform: 'uppercase',
  },
  shortcutsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginBottom: 24,
  },
  shortcutCard: {
    width: '48%',
    backgroundColor: theme.colors.white,
    borderWidth: 1,
    borderColor: theme.colors.gray200,
    borderRadius: theme.radii.base,
    padding: 14,
    marginBottom: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    ...theme.shadows.sm,
  },
  shortcutLabel: {
    fontSize: 12,
    fontWeight: theme.typography.fontBold,
    color: theme.colors.black,
    flex: 1,
    marginRight: 6,
  },
  shortcutIconBox: {
    width: 32,
    height: 32,
    borderRadius: 8,
    backgroundColor: theme.colors.gray100,
    justifyContent: 'center',
    alignItems: 'center',
  },
  venueCard: {
    backgroundColor: theme.colors.white,
    borderWidth: 1,
    borderColor: theme.colors.gray200,
    borderRadius: theme.radii.base,
    padding: 14,
    marginBottom: 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    ...theme.shadows.sm,
  },
  venueInfo: {
    flex: 1,
    marginRight: 10,
  },
  venueName: {
    fontSize: 14,
    fontWeight: theme.typography.fontBold,
    color: theme.colors.black,
  },
  venueLocation: {
    fontSize: 11,
    color: theme.colors.gray500,
    marginTop: 2,
  },
  venueActions: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  venueActionBtn: {
    width: 34,
    height: 34,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: theme.colors.black,
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 8,
  },
  venueActionBtnPrimary: {
    backgroundColor: theme.colors.black,
  },
  emptyState: {
    padding: 24,
    backgroundColor: theme.colors.gray50,
    borderRadius: theme.radii.base,
    borderWidth: 1,
    borderColor: theme.colors.gray200,
    borderStyle: 'dashed',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 20,
  },
  emptyStateText: {
    fontSize: 12,
    color: theme.colors.gray500,
    textAlign: 'center',
  },
  vitalsPanel: {
    backgroundColor: theme.colors.white,
    borderWidth: 1,
    borderColor: theme.colors.gray200,
    borderRadius: theme.radii.base,
    padding: 12,
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
  },
  statusDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#10b981', // emerald-500 online
    marginRight: 8,
  },
  statusText: {
    fontSize: 11,
    fontWeight: theme.typography.fontBold,
    color: theme.colors.black,
    letterSpacing: 0.5,
  },
});
