from .linear_regression import train_linear_regression
from .polynomial_regression import train_polynomial_regression
from .ridge_regression import train_ridge_regression
from .lasso_regression import train_lasso_regression
