server:
  port: 8000

spring:
  application:
    name: laika-gateway
  
  datasource:
    mysql:
      url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/${MYSQL_DATABASE:laika_club3_v2}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      username: ${MYSQL_USER:root}
      password: ${MYSQL_PASSWORD:}
      driver-class-name: com.mysql.cj.jdbc.Driver

# Routing configurations for the microservices
services:
  auth: ${AUTH_SERVICE_URL:http://localhost:8101}
  events: ${EVENTS_SERVICE_URL:http://localhost:8201}
  tickets: ${TICKETS_SERVICE_URL:http://localhost:8202}
  stats: ${STATS_SERVICE_URL:http://localhost:8103}
  admin: ${ADMIN_SERVICE_URL:http://localhost:8102}
  achievements: ${ACHIEVEMENTS_SERVICE_URL:http://localhost:8301}
  analytics: ${ANALYTICS_SERVICE_URL:http://localhost:8302}
  analytics_bigdata: ${ANALYTICS_BIGDATA_SERVICE_URL:http://localhost:8303}
  merchandise: ${MERCHANDISE_SERVICE_URL:http://localhost:8203}
